{
 "title": "System Event Internals",
 "description": "Dashboard for monitoring internal metrics of the system event service",
 "tags": [
  "prometheus",
  "system-event",
  "http-service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "client",
    "query": "label_values(client_attempt_total, Client)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({service=~\"system-events.*\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Http Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Requests (per second)",
     "type": "graph",
     "description": "Per second rate of successful (2xx) http requests",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{service=~\"$service\", code=~\"2\\\\d\\\\d\"}[1m])) without (instance)",
       "legendFormat": "{{code}} {{method}} {{controller}}.{{action}}"
      }
     ]
    },
    {
     "title": "Non 2xx Http Requests (per second)",
     "type": "graph",
     "description": "Per second rate of non-2xx http requests",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{service=~\"$service\", code !~\"2\\\\d\\\\d\"}[1m])) without (instance)",
       "legendFormat": "{{code}} {{method}} {{controller}}.{{action}} "
      }
     ]
    },
    {
     "title": "In Progress Requests",
     "type": "graph",
     "description": "The number of requests currently in progress in the ASP.NET Core pipeline. One series without controller/action label values counts all in-progress requests, with separate series existing for each controller-action pair",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_requests_in_progress{service=~\"$service\"}) without (instance)",
       "legendFormat": "{{method}} {{controller}}.{{action}}"
      }
     ]
    },
    {
     "title": "Http Average Request Duration ",
     "type": "graph",
     "description": "Http request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{service=~\"$service\"}[1m])) without (instance) / sum(rate(http_request_duration_seconds_count{service=~\"$service\"}[1m])) without (instance)",
       "legendFormat": "{{code}} {{method}} {{Controller}}.{{action}}"
      }
     ]
    },
    {
     "title": "Http Request Duration P99",
     "type": "graph",
     "description": "Percentile 99 of http request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\"}[10m])) without (instance))",
       "legendFormat": "{{code}} {{method}} {{Controller}}.{{action}}"
      }
     ]
    },
    {
     "title": "Http Request Duration P95",
     "type": "graph",
     "description": "Percentile 95 of http request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service=~\"$service\"}[10m])) without (instance))",
       "legendFormat": "{{code}} {{method}} {{Controller}}.{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "client",
   "collapsed": true,
   "panels": [
    {
     "title": "$client Method Invoke (per second)",
     "type": "graph",
     "description": "Per second rate of total $client Method Invoke",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_attempt_total{Client=~\"$client\", service=~\"$service\"}[1m])) by (Method)",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "$client Errors (per second)",
     "type": "graph",
     "description": "Per second rate of total  $client errors",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_fail_total{Client=~\"$client\", service=~\"$service\"}[1m])) by (Method)",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "$client Average Request Duration ",
     "type": "graph",
     "description": "$client  request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_duration_seconds_sum{service=~\"$service\", Client=~\"$client\"}[1m])) by (Method) / sum(rate(client_duration_seconds_count{service=~\"$service\", Client=~\"$client\"}[1m])) by (Method)",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "$client Request Duration P99",
     "type": "graph",
     "description": "Percentile 99 of $client request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(client_duration_seconds_bucket{service=~\"$service\", Client=~\"$client\"}[10m])) by (Method))",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "$client Request Duration P95",
     "type": "graph",
     "description": "Percentile 95 of $client request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(client_duration_seconds_bucket{service=~\"$service\", Client=~\"$client\"}[10m])) by (Method))",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "$client Request Duration P90",
     "type": "graph",
     "description": "Percentile 90 of $client request duration in milliseconds ",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(client_duration_seconds_bucket{service=~\"$service\", Client=~\"$client\"}[10m])) by (Method))",
       "legendFormat": "{{Method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dotnet Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "description": "Per second rate of total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{service=~\"$service\"}[1m]) * 60"
      }
     ]
    },
    {
     "title": "Dotnet Total Memory",
     "type": "graph",
     "description": "The number of bytes currently thought to be allocated given by the GC.GetTotalMemory method. Read more at https://docs.microsoft.com/en-us/dotnet/api/system.gc.gettotalmemory?view=netframework-4.8",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(dotnet_total_memory_bytes{service=~\"$service\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of threads",
     "type": "graph",
     "description": "Current total number of threads ",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_num_threads{service=~\"$service\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "description": "Represents the current size of working set memory used by the process, in bytes. The working set of a process is the set of memory pages currently visible to the process in physical RAM memory. These pages are resident and available for an application to use without triggering a page fault.\n\nThe working set includes both shared and private data. The shared data includes the pages that contain all the instructions that the process executes, including instructions in the process modules and the system libraries.\n\nThis property can be used to monitor memory usage on computers with 32-bit processors or 64-bit processors. The property value is equivalent to the Working Set performance counter for the process. See https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.workingset64?view=netcore-2.2",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_working_set_bytes{service=~\"$service\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Garbage Collection ",
     "type": "graph",
     "description": "Garbage Collection metrics. (per minute)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dotnet_collection_errors_total{service=~\"$service\"}[1m])",
       "legendFormat": "collection errors"
      },
      {
       "expr": "rate(dotnet_collection_count_total{service=~\"$service\"}[1m])",
       "legendFormat": "collection count {{generation}}"
      }
     ]
    },
    {
     "title": "Process Open Handles",
     "type": "graph",
     "description": "Number of open handles",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_handles{service=~\"$service\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}